// <auto-generated />
namespace InstagramWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Instapost : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Instapost));
        
        string IMigrationMetadata.Id
        {
            get { return "202005232049057_Instapost"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
